// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chats.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chat struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Users                []int64  `protobuf:"varint,3,rep,packed,name=users,proto3" json:"users,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05cf9748eb56a00, []int{0}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chat) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Chat) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type ChatsAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Users                []int64  `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatsAddRequest) Reset()         { *m = ChatsAddRequest{} }
func (m *ChatsAddRequest) String() string { return proto.CompactTextString(m) }
func (*ChatsAddRequest) ProtoMessage()    {}
func (*ChatsAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05cf9748eb56a00, []int{1}
}

func (m *ChatsAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatsAddRequest.Unmarshal(m, b)
}
func (m *ChatsAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatsAddRequest.Marshal(b, m, deterministic)
}
func (m *ChatsAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatsAddRequest.Merge(m, src)
}
func (m *ChatsAddRequest) XXX_Size() int {
	return xxx_messageInfo_ChatsAddRequest.Size(m)
}
func (m *ChatsAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatsAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatsAddRequest proto.InternalMessageInfo

func (m *ChatsAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatsAddRequest) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type ChatsAddResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatsAddResponse) Reset()         { *m = ChatsAddResponse{} }
func (m *ChatsAddResponse) String() string { return proto.CompactTextString(m) }
func (*ChatsAddResponse) ProtoMessage()    {}
func (*ChatsAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05cf9748eb56a00, []int{2}
}

func (m *ChatsAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatsAddResponse.Unmarshal(m, b)
}
func (m *ChatsAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatsAddResponse.Marshal(b, m, deterministic)
}
func (m *ChatsAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatsAddResponse.Merge(m, src)
}
func (m *ChatsAddResponse) XXX_Size() int {
	return xxx_messageInfo_ChatsAddResponse.Size(m)
}
func (m *ChatsAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatsAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatsAddResponse proto.InternalMessageInfo

func (m *ChatsAddResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChatsGetRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatsGetRequest) Reset()         { *m = ChatsGetRequest{} }
func (m *ChatsGetRequest) String() string { return proto.CompactTextString(m) }
func (*ChatsGetRequest) ProtoMessage()    {}
func (*ChatsGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05cf9748eb56a00, []int{3}
}

func (m *ChatsGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatsGetRequest.Unmarshal(m, b)
}
func (m *ChatsGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatsGetRequest.Marshal(b, m, deterministic)
}
func (m *ChatsGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatsGetRequest.Merge(m, src)
}
func (m *ChatsGetRequest) XXX_Size() int {
	return xxx_messageInfo_ChatsGetRequest.Size(m)
}
func (m *ChatsGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatsGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatsGetRequest proto.InternalMessageInfo

func (m *ChatsGetRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

type ChatsGetResponse struct {
	Chats                []*Chat  `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatsGetResponse) Reset()         { *m = ChatsGetResponse{} }
func (m *ChatsGetResponse) String() string { return proto.CompactTextString(m) }
func (*ChatsGetResponse) ProtoMessage()    {}
func (*ChatsGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05cf9748eb56a00, []int{4}
}

func (m *ChatsGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatsGetResponse.Unmarshal(m, b)
}
func (m *ChatsGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatsGetResponse.Marshal(b, m, deterministic)
}
func (m *ChatsGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatsGetResponse.Merge(m, src)
}
func (m *ChatsGetResponse) XXX_Size() int {
	return xxx_messageInfo_ChatsGetResponse.Size(m)
}
func (m *ChatsGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatsGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatsGetResponse proto.InternalMessageInfo

func (m *ChatsGetResponse) GetChats() []*Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

func init() {
	proto.RegisterType((*Chat)(nil), "Chat")
	proto.RegisterType((*ChatsAddRequest)(nil), "ChatsAddRequest")
	proto.RegisterType((*ChatsAddResponse)(nil), "ChatsAddResponse")
	proto.RegisterType((*ChatsGetRequest)(nil), "ChatsGetRequest")
	proto.RegisterType((*ChatsGetResponse)(nil), "ChatsGetResponse")
}

func init() { proto.RegisterFile("chats.proto", fileDescriptor_a05cf9748eb56a00) }

var fileDescriptor_a05cf9748eb56a00 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xd3, 0x0a, 0x7b, 0x03, 0x9d, 0xc1, 0x43, 0x51, 0x84, 0x12, 0x10, 0xea, 0x64,
	0x2d, 0xcc, 0xa3, 0xa7, 0x2a, 0xb2, 0x7b, 0x8f, 0x5e, 0x4a, 0xd6, 0x3c, 0x6c, 0xd1, 0xb5, 0x35,
	0x79, 0x3d, 0xf8, 0xdf, 0x4b, 0xb3, 0xcc, 0x95, 0xe9, 0xed, 0xe5, 0xf1, 0xf9, 0xfe, 0x48, 0x02,
	0xf3, 0xaa, 0x96, 0x64, 0xd2, 0x5e, 0x77, 0xd4, 0x89, 0x12, 0x82, 0x97, 0x5a, 0x12, 0x3f, 0x07,
	0xbf, 0x51, 0x91, 0x17, 0x7b, 0x09, 0x2b, 0xfc, 0x46, 0x71, 0x0e, 0x41, 0x2b, 0x77, 0x18, 0xf9,
	0xb1, 0x97, 0xcc, 0x0a, 0x3b, 0xf3, 0x2b, 0x08, 0x07, 0x83, 0xda, 0x44, 0x2c, 0x66, 0x09, 0x2b,
	0xf6, 0x07, 0x7e, 0x0b, 0x50, 0x69, 0x94, 0x84, 0xaa, 0x94, 0x14, 0x05, 0x96, 0x9f, 0xb9, 0x4d,
	0x4e, 0xe2, 0x09, 0x2e, 0xc6, 0x00, 0x93, 0x2b, 0x55, 0xe0, 0xd7, 0x80, 0x86, 0x7e, 0xbd, 0xbd,
	0xff, 0xbc, 0xfd, 0x89, 0xb7, 0x10, 0xb0, 0x38, 0x8a, 0x4d, 0xdf, 0xb5, 0x06, 0x4f, 0x9b, 0x8a,
	0x3b, 0x17, 0xb0, 0x41, 0x9a, 0x04, 0x8c, 0x7a, 0x07, 0xd9, 0x59, 0x64, 0xce, 0xca, 0x62, 0xce,
	0xea, 0x06, 0x42, 0xfb, 0x16, 0x91, 0x17, 0xb3, 0x64, 0xbe, 0x0e, 0xd3, 0x91, 0x28, 0xf6, 0xbb,
	0x75, 0x09, 0xa1, 0x15, 0xf0, 0x25, 0xb0, 0x5c, 0x29, 0xbe, 0x48, 0x4f, 0xee, 0x71, 0x7d, 0x99,
	0xfe, 0x29, 0xb7, 0x04, 0xb6, 0x41, 0x3a, 0xb0, 0xc7, 0x4a, 0x07, 0x76, 0x92, 0xfe, 0xfc, 0xf0,
	0x76, 0xff, 0xde, 0x50, 0x3d, 0x6c, 0xd3, 0xaa, 0xdb, 0x65, 0x4a, 0x92, 0xfc, 0x6c, 0xda, 0x8f,
	0xd7, 0xec, 0x1b, 0x69, 0x25, 0xdb, 0x8e, 0x6a, 0xd4, 0xab, 0xb1, 0x4a, 0xa6, 0xfb, 0x6a, 0x7b,
	0x66, 0xbf, 0xeb, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xec, 0x36, 0x2e, 0xbd, 0x01, 0x00,
	0x00,
}
