// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chats.proto

package rpc // import "github.com/datalinkE/yet-another-chat/rpc"

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Chat) Validate() error {
	return nil
}
func (this *ChatsAddRequest) Validate() error {
	return nil
}
func (this *ChatsAddResponse) Validate() error {
	return nil
}
func (this *ChatsGetRequest) Validate() error {
	return nil
}
func (this *ChatsGetResponse) Validate() error {
	for _, item := range this.Chats {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Chats", err)
			}
		}
	}
	return nil
}
