// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Chat                 int64    `protobuf:"varint,2,opt,name=chat,proto3" json:"chat,omitempty"`
	Author               int64    `protobuf:"varint,3,opt,name=author,proto3" json:"author,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetChat() int64 {
	if m != nil {
		return m.Chat
	}
	return 0
}

func (m *Message) GetAuthor() int64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type MessagesAddRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Users                []int64  `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesAddRequest) Reset()         { *m = MessagesAddRequest{} }
func (m *MessagesAddRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesAddRequest) ProtoMessage()    {}
func (*MessagesAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *MessagesAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesAddRequest.Unmarshal(m, b)
}
func (m *MessagesAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesAddRequest.Marshal(b, m, deterministic)
}
func (m *MessagesAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesAddRequest.Merge(m, src)
}
func (m *MessagesAddRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesAddRequest.Size(m)
}
func (m *MessagesAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesAddRequest proto.InternalMessageInfo

func (m *MessagesAddRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MessagesAddRequest) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type MessagesAddResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesAddResponse) Reset()         { *m = MessagesAddResponse{} }
func (m *MessagesAddResponse) String() string { return proto.CompactTextString(m) }
func (*MessagesAddResponse) ProtoMessage()    {}
func (*MessagesAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *MessagesAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesAddResponse.Unmarshal(m, b)
}
func (m *MessagesAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesAddResponse.Marshal(b, m, deterministic)
}
func (m *MessagesAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesAddResponse.Merge(m, src)
}
func (m *MessagesAddResponse) XXX_Size() int {
	return xxx_messageInfo_MessagesAddResponse.Size(m)
}
func (m *MessagesAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesAddResponse proto.InternalMessageInfo

func (m *MessagesAddResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MessagesGetRequest struct {
	Chat                 int64    `protobuf:"varint,1,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesGetRequest) Reset()         { *m = MessagesGetRequest{} }
func (m *MessagesGetRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesGetRequest) ProtoMessage()    {}
func (*MessagesGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *MessagesGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesGetRequest.Unmarshal(m, b)
}
func (m *MessagesGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesGetRequest.Marshal(b, m, deterministic)
}
func (m *MessagesGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesGetRequest.Merge(m, src)
}
func (m *MessagesGetRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesGetRequest.Size(m)
}
func (m *MessagesGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesGetRequest proto.InternalMessageInfo

func (m *MessagesGetRequest) GetChat() int64 {
	if m != nil {
		return m.Chat
	}
	return 0
}

type MessagesGetResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessagesGetResponse) Reset()         { *m = MessagesGetResponse{} }
func (m *MessagesGetResponse) String() string { return proto.CompactTextString(m) }
func (*MessagesGetResponse) ProtoMessage()    {}
func (*MessagesGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *MessagesGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesGetResponse.Unmarshal(m, b)
}
func (m *MessagesGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesGetResponse.Marshal(b, m, deterministic)
}
func (m *MessagesGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesGetResponse.Merge(m, src)
}
func (m *MessagesGetResponse) XXX_Size() int {
	return xxx_messageInfo_MessagesGetResponse.Size(m)
}
func (m *MessagesGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesGetResponse proto.InternalMessageInfo

func (m *MessagesGetResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*MessagesAddRequest)(nil), "MessagesAddRequest")
	proto.RegisterType((*MessagesAddResponse)(nil), "MessagesAddResponse")
	proto.RegisterType((*MessagesGetRequest)(nil), "MessagesGetRequest")
	proto.RegisterType((*MessagesGetResponse)(nil), "MessagesGetResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcf, 0x6b, 0xea, 0x40,
	0x10, 0x26, 0x59, 0xf5, 0xc5, 0x79, 0xe0, 0x61, 0x95, 0xb2, 0x08, 0x85, 0x10, 0x5a, 0x48, 0x29,
	0x46, 0xb1, 0xc7, 0x9e, 0x2c, 0xb4, 0x9e, 0x7a, 0xc9, 0xb1, 0x97, 0xb2, 0x66, 0x07, 0x13, 0x5a,
	0xb3, 0x76, 0x77, 0x02, 0xf6, 0xbf, 0x2f, 0xae, 0x89, 0x49, 0xb1, 0xb7, 0x99, 0x6f, 0x66, 0xbe,
	0x1f, 0xbb, 0x30, 0xda, 0xa1, 0xb5, 0x72, 0x8b, 0x36, 0xd9, 0x1b, 0x4d, 0x3a, 0x3a, 0xc0, 0xbf,
	0xd7, 0x13, 0xc2, 0x47, 0xe0, 0x17, 0x4a, 0x78, 0xa1, 0x17, 0xb3, 0xd4, 0x2f, 0x14, 0xe7, 0xd0,
	0xcb, 0x72, 0x49, 0xc2, 0x77, 0x88, 0xab, 0xf9, 0x15, 0x0c, 0x64, 0x45, 0xb9, 0x36, 0x82, 0x39,
	0xb4, 0xee, 0x8e, 0xbb, 0x84, 0x07, 0x12, 0xbd, 0xd0, 0x8b, 0x87, 0xa9, 0xab, 0xf9, 0x35, 0x40,
	0x66, 0x50, 0x12, 0xaa, 0x77, 0x49, 0xa2, 0xef, 0x26, 0xc3, 0x1a, 0x59, 0x51, 0xf4, 0x02, 0xbc,
	0x56, 0xb6, 0x2b, 0xa5, 0x52, 0xfc, 0xaa, 0xd0, 0x12, 0x9f, 0x42, 0x50, 0x59, 0x34, 0xa5, 0xdc,
	0xa1, 0xb3, 0x32, 0x4c, 0xcf, 0x3d, 0x9f, 0x40, 0xff, 0x58, 0x5b, 0xe1, 0x87, 0x2c, 0x66, 0xe9,
	0xa9, 0x89, 0x6e, 0x61, 0xfc, 0x8b, 0xc7, 0xee, 0x75, 0x69, 0x2f, 0xd2, 0x44, 0x71, 0x2b, 0xb7,
	0x46, 0x6a, 0xe4, 0x9a, 0x8c, 0x5e, 0x9b, 0x31, 0x7a, 0x6c, 0x09, 0xdd, 0x66, 0x4d, 0x78, 0x03,
	0x41, 0xf3, 0x76, 0xc2, 0x0b, 0x59, 0xfc, 0x7f, 0x19, 0x24, 0xf5, 0x5e, 0x7a, 0x9e, 0x2c, 0x4b,
	0x08, 0x9a, 0x63, 0xbe, 0x00, 0xb6, 0x52, 0x8a, 0x8f, 0x93, 0xcb, 0x9c, 0xd3, 0x49, 0xf2, 0x97,
	0xe9, 0x05, 0xb0, 0x35, 0x52, 0xe7, 0xa2, 0xb5, 0xda, 0xb9, 0xe8, 0xb8, 0x7a, 0xba, 0x7f, 0xbb,
	0xdb, 0x16, 0x94, 0x57, 0x9b, 0x24, 0xd3, 0xbb, 0xb9, 0x92, 0x24, 0x3f, 0x8b, 0xf2, 0xe3, 0x79,
	0xfe, 0x8d, 0x34, 0x93, 0xa5, 0xa6, 0x1c, 0xcd, 0xec, 0x98, 0x6a, 0x6e, 0xf6, 0xd9, 0x66, 0xe0,
	0xfe, 0xfc, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x20, 0xab, 0x98, 0x05, 0x02, 0x00, 0x00,
}
