// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// @inject_tag: storm:"id,increment"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" storm:"id,increment"`
	// @inject_tag: storm:"unique"
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" storm:"unique"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type UsersAddRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersAddRequest) Reset()         { *m = UsersAddRequest{} }
func (m *UsersAddRequest) String() string { return proto.CompactTextString(m) }
func (*UsersAddRequest) ProtoMessage()    {}
func (*UsersAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *UsersAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAddRequest.Unmarshal(m, b)
}
func (m *UsersAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAddRequest.Marshal(b, m, deterministic)
}
func (m *UsersAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAddRequest.Merge(m, src)
}
func (m *UsersAddRequest) XXX_Size() int {
	return xxx_messageInfo_UsersAddRequest.Size(m)
}
func (m *UsersAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAddRequest proto.InternalMessageInfo

func (m *UsersAddRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UsersAddResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersAddResponse) Reset()         { *m = UsersAddResponse{} }
func (m *UsersAddResponse) String() string { return proto.CompactTextString(m) }
func (*UsersAddResponse) ProtoMessage()    {}
func (*UsersAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *UsersAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAddResponse.Unmarshal(m, b)
}
func (m *UsersAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAddResponse.Marshal(b, m, deterministic)
}
func (m *UsersAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAddResponse.Merge(m, src)
}
func (m *UsersAddResponse) XXX_Size() int {
	return xxx_messageInfo_UsersAddResponse.Size(m)
}
func (m *UsersAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAddResponse proto.InternalMessageInfo

func (m *UsersAddResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UsersGetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersGetRequest) Reset()         { *m = UsersGetRequest{} }
func (m *UsersGetRequest) String() string { return proto.CompactTextString(m) }
func (*UsersGetRequest) ProtoMessage()    {}
func (*UsersGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *UsersGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersGetRequest.Unmarshal(m, b)
}
func (m *UsersGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersGetRequest.Marshal(b, m, deterministic)
}
func (m *UsersGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersGetRequest.Merge(m, src)
}
func (m *UsersGetRequest) XXX_Size() int {
	return xxx_messageInfo_UsersGetRequest.Size(m)
}
func (m *UsersGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersGetRequest proto.InternalMessageInfo

type UsersGetResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersGetResponse) Reset()         { *m = UsersGetResponse{} }
func (m *UsersGetResponse) String() string { return proto.CompactTextString(m) }
func (*UsersGetResponse) ProtoMessage()    {}
func (*UsersGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *UsersGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersGetResponse.Unmarshal(m, b)
}
func (m *UsersGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersGetResponse.Marshal(b, m, deterministic)
}
func (m *UsersGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersGetResponse.Merge(m, src)
}
func (m *UsersGetResponse) XXX_Size() int {
	return xxx_messageInfo_UsersGetResponse.Size(m)
}
func (m *UsersGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersGetResponse proto.InternalMessageInfo

func (m *UsersGetResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UsersAddRequest)(nil), "UsersAddRequest")
	proto.RegisterType((*UsersAddResponse)(nil), "UsersAddResponse")
	proto.RegisterType((*UsersGetRequest)(nil), "UsersGetRequest")
	proto.RegisterType((*UsersGetResponse)(nil), "UsersGetResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0x6b, 0xc5, 0xbd, 0x81, 0x6e, 0x39, 0x95, 0x89, 0x50, 0x72, 0xaa, 0x93, 0xa6,
	0x30, 0x3f, 0x41, 0x05, 0xd9, 0xd9, 0x82, 0x17, 0x2f, 0x23, 0x6b, 0x1e, 0xb6, 0xe8, 0x9a, 0x9a,
	0xbc, 0x1e, 0xfc, 0xf6, 0xd2, 0x98, 0x39, 0xb7, 0x1d, 0xf3, 0xf2, 0xfb, 0xff, 0xde, 0x3f, 0x81,
	0xe9, 0x60, 0xd1, 0x58, 0xd1, 0x1b, 0x4d, 0x9a, 0xbf, 0xc0, 0xc5, 0xab, 0x45, 0xc3, 0xae, 0x21,
	0x6c, 0x55, 0x12, 0xa4, 0x41, 0x16, 0x55, 0x61, 0xab, 0xd8, 0x02, 0xae, 0x46, 0xac, 0x93, 0x3b,
	0x4c, 0xc2, 0x34, 0xc8, 0x26, 0xd5, 0xdf, 0x99, 0xdd, 0x01, 0xd4, 0x06, 0x25, 0xa1, 0xda, 0x48,
	0x4a, 0x22, 0x77, 0x3b, 0xf1, 0x93, 0x92, 0x78, 0x0e, 0x37, 0xa3, 0xd2, 0x96, 0x4a, 0x55, 0xf8,
	0x35, 0xa0, 0xa5, 0x23, 0x5b, 0x70, 0x6c, 0xe3, 0x1c, 0x66, 0x07, 0xdc, 0xf6, 0xba, 0xb3, 0x78,
	0xda, 0x86, 0xcf, 0xbd, 0x72, 0x8d, 0xe4, 0x95, 0xbc, 0xf0, 0x31, 0x37, 0xf2, 0xb1, 0x5b, 0x88,
	0xdd, 0xdb, 0x92, 0x20, 0x8d, 0xb2, 0xe9, 0x2a, 0x16, 0x23, 0x51, 0xfd, 0xce, 0x56, 0x1b, 0x88,
	0x5d, 0x80, 0x2d, 0x21, 0x2a, 0x95, 0x62, 0x33, 0x71, 0xd2, 0x72, 0x31, 0x17, 0x67, 0x45, 0x96,
	0x10, 0xad, 0x91, 0xf6, 0xec, 0x61, 0xfd, 0x9e, 0xfd, 0xb7, 0xfd, 0xe9, 0xe1, 0xed, 0xfe, 0xbd,
	0xa5, 0x66, 0xd8, 0x8a, 0x5a, 0xef, 0x0a, 0x25, 0x49, 0x7e, 0xb6, 0xdd, 0xc7, 0x73, 0xf1, 0x8d,
	0x94, 0xcb, 0x4e, 0x53, 0x83, 0x26, 0xaf, 0x1b, 0x49, 0x85, 0xe9, 0xeb, 0xed, 0xa5, 0xfb, 0xfe,
	0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x78, 0x32, 0x46, 0x8d, 0x01, 0x00, 0x00,
}
