// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package rpc // import "github.com/datalinkE/yet-another-chat/rpc"

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	return nil
}
func (this *UsersAddRequest) Validate() error {
	return nil
}
func (this *UsersAddResponse) Validate() error {
	return nil
}
func (this *UsersGetRequest) Validate() error {
	return nil
}
func (this *UsersGetResponse) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
